chore: format before lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,15 +2,15 @@
 
 echo '👷‍♂️ Starting pre-commit checks...'
 
-echo '🧹 Linting ...'
-bun lint . --ext .ts,.tsx || {
-  echo '❌ Linting failed. Please fix the errors before committing.'
-  exit 1
-}
-
 echo '🎨 Formatting ...'
 bun format || {
   echo '❌ Formatting failed.'
+  exit 1
+}
+
+echo '🧹 Linting ...'
+bun lint . --ext .ts,.tsx || {
+  echo '❌ Linting failed. Please fix the errors before committing.'
   exit 1
 }
 
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,15 +2,15 @@
 
 echo '🚀 Starting pre-push checks...'
 
-echo '🔍 Linting ...'
-bun lint || {
-  echo '❌ Linting failed. Please fix linting errors before pushing.'
-  exit 1
-}
-
 echo '🎨 Formatting ...'
 bun format || {
   echo '❌ Formatting failed. Please fix formatting errors before pushing.'
+  exit 1
+}
+
+echo '🔍 Linting ...'
+bun lint || {
+  echo '❌ Linting failed. Please fix linting errors before pushing.'
   exit 1
 }
 
